/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.UnsupportedEncodingException;
import java.net.MalformedURLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import urnaclient.UrnaClient;

/**
 *
 * @author Admin
 */
public class FrameCadastroEleitor extends javax.swing.JFrame {

    /**
     * Creates new form FrameCadastroEleitor
     */
    public FrameCadastroEleitor() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Cadastro de eleitor");
        btn_atualizar_eleitor.setEnabled(false);
        btn_excluir_eleitor.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_cad_eleitor_nome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_cadastrar_eleitor = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        txt_cad_eleitor_titulo = new javax.swing.JFormattedTextField();
        txt_cad_eleitor_zona = new javax.swing.JFormattedTextField();
        txt_cad_eleitor_sessao = new javax.swing.JFormattedTextField();
        btn_atualizar_eleitor = new javax.swing.JButton();
        btn_excluir_eleitor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nome:");

        jLabel2.setText("Título:");

        jLabel3.setText("Zona:");

        jLabel4.setText("Sessão:");

        btn_cadastrar_eleitor.setText("Cadastrar");
        btn_cadastrar_eleitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrar_eleitorActionPerformed(evt);
            }
        });

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        try {
            txt_cad_eleitor_titulo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#### #### ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_cad_eleitor_titulo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_cad_eleitor_tituloFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_cad_eleitor_tituloFocusLost(evt);
            }
        });

        try {
            txt_cad_eleitor_zona.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txt_cad_eleitor_sessao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btn_atualizar_eleitor.setText("Atualizar");
        btn_atualizar_eleitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atualizar_eleitorActionPerformed(evt);
            }
        });

        btn_excluir_eleitor.setText("Excluir");
        btn_excluir_eleitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluir_eleitorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(txt_cad_eleitor_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(229, 229, 229))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(txt_cad_eleitor_zona, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(65, 65, 65)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(txt_cad_eleitor_sessao, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btn_cancelar)
                                    .addGap(46, 46, 46)
                                    .addComponent(btn_excluir_eleitor, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btn_atualizar_eleitor)))
                            .addGap(10, 10, 10)
                            .addComponent(btn_cadastrar_eleitor))
                        .addComponent(txt_cad_eleitor_nome)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_cad_eleitor_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_cad_eleitor_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_cadastrar_eleitor)
                            .addComponent(btn_cancelar)
                            .addComponent(btn_atualizar_eleitor)
                            .addComponent(btn_excluir_eleitor))
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_cad_eleitor_zona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_cad_eleitor_sessao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(78, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cadastrar_eleitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrar_eleitorActionPerformed
        UrnaClient uc = new UrnaClient();
        if (txt_cad_eleitor_nome.getText().isEmpty() || txt_cad_eleitor_sessao.getText().contains(" ")
                || txt_cad_eleitor_titulo.getText().contains("  ") || txt_cad_eleitor_zona.getText().contains(" ")) {
            JOptionPane.showMessageDialog(null, "Preencha os campos corretamente.");
        } else {
            try {
                uc.cadastrarEleitor(txt_cad_eleitor_nome.getText(), txt_cad_eleitor_titulo.getText(), txt_cad_eleitor_zona.getText(), txt_cad_eleitor_sessao.getText());
            } catch (MalformedURLException ex) {
                Logger.getLogger(FrameCadastroEleitor.class.getName()).log(Level.SEVERE, null, ex);
            } catch (UnsupportedEncodingException ex) {
                Logger.getLogger(FrameCadastroEleitor.class.getName()).log(Level.SEVERE, null, ex);
            }
            dispose();
        }   
    }//GEN-LAST:event_btn_cadastrar_eleitorActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void txt_cad_eleitor_tituloFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cad_eleitor_tituloFocusLost
        UrnaClient uc = new UrnaClient();

        try {
            if (uc.verificarEleitor(txt_cad_eleitor_titulo.getText()) == true) {
                String[] eleitor = uc.preencherCadastroEleitor(txt_cad_eleitor_titulo.getText());
                txt_cad_eleitor_nome.setText(eleitor[0]);
                txt_cad_eleitor_zona.setText(eleitor[2]);
                txt_cad_eleitor_sessao.setText(eleitor[3]);
                btn_atualizar_eleitor.setEnabled(true);
                btn_excluir_eleitor.setEnabled(true);
            }
        } catch (MalformedURLException ex) {
            Logger.getLogger(FrameCadastroEleitor.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_txt_cad_eleitor_tituloFocusLost

    private void btn_excluir_eleitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluir_eleitorActionPerformed
        int resp = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja excluir " + txt_cad_eleitor_nome.getText() + " do registro?");
        if (resp == 0) {
            try {
                UrnaClient uc = new UrnaClient();
                uc.apagarEleitor(txt_cad_eleitor_titulo.getText());
                dispose();
            } catch (MalformedURLException ex) {
                Logger.getLogger(FrameCadastroEleitor.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_btn_excluir_eleitorActionPerformed

    private void btn_atualizar_eleitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atualizar_eleitorActionPerformed
        UrnaClient uc = new UrnaClient();
        if (txt_cad_eleitor_nome.getText().isEmpty() || txt_cad_eleitor_sessao.getText().contains(" ")
                || txt_cad_eleitor_titulo.getText().contains("  ") || txt_cad_eleitor_zona.getText().contains(" ")) {
            JOptionPane.showMessageDialog(null, "Preencha os campos corretamente.");
        } else {
            try {
                uc.atualizarEleitor(txt_cad_eleitor_titulo.getText(), txt_cad_eleitor_nome.getText(),
                        txt_cad_eleitor_zona.getText(), txt_cad_eleitor_sessao.getText());
            } catch (MalformedURLException ex) {
                Logger.getLogger(FrameCadastroEleitor.class.getName()).log(Level.SEVERE, null, ex);
            }
          dispose();
        }
    }//GEN-LAST:event_btn_atualizar_eleitorActionPerformed

    private void txt_cad_eleitor_tituloFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cad_eleitor_tituloFocusGained
        btn_atualizar_eleitor.setEnabled(false);
        btn_excluir_eleitor.setEnabled(false);
    }//GEN-LAST:event_txt_cad_eleitor_tituloFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameCadastroEleitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameCadastroEleitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameCadastroEleitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameCadastroEleitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameCadastroEleitor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_atualizar_eleitor;
    private javax.swing.JButton btn_cadastrar_eleitor;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_excluir_eleitor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JTextField txt_cad_eleitor_nome;
    public javax.swing.JFormattedTextField txt_cad_eleitor_sessao;
    public javax.swing.JFormattedTextField txt_cad_eleitor_titulo;
    public javax.swing.JFormattedTextField txt_cad_eleitor_zona;
    // End of variables declaration//GEN-END:variables
}
